apiVersion: v2
name: nexus-iq-server-ha
version: 151.0.0
appVersion: 1.151.0
description: A cluster of Sonatype Nexus IQ Servers to continuously monitor your entire software supply chain
type: application
keywords:
  - sonatype
  - nexus
  - lifecycle
  - iq
  - remediate
  - vulnerabilities
  - policy
home: https://www.sonatype.com/product-nexus-lifecycle
maintainers:
  - email: support@sonatype.com
    name: Sonatype
dependencies:
  - name: postgresql
    version: 12.1.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - development
  - name: ingress-nginx
    version: 4.4.2
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: fluentd
    repository: https://charts.bitnami.com/bitnami
    version: 5.5.12
    condition: fluentd.enabled
  - name: elasticsearch
    repository: https://charts.bitnami.com/bitnami
    version: 19.5.6
    condition: elasticsearch.enabled
    tags:
      - development
