{{- if and .Values.hpa.enabled (or (.Values.hpa.triggers.cpu.enabled) (.Values.hpa.triggers.memory.enabled)) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-iq-server-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-iq-server-deployment
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{- if .Values.hpa.triggers.cpu.enabled }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.triggers.cpu.threshold }}
  {{- end }}
  {{- if .Values.hpa.triggers.memory.enabled }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.hpa.triggers.memory.threshold }}
  {{- end }}
{{- end }}